<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Bonsai Library for real-time multi-pose tracking using SLEAP-NN with ONNX Runtime CUDA and TensorRT execution providers.</Description>
    <PackageTags>$(PackageTags) Gpu</PackageTags>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.24.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bonsai.Sleap\Bonsai.Sleap.csproj" />
  </ItemGroup>

</Project>
